"""new_migration_test

Revision ID: a757914543ac
Revises: add_email_parsing
Create Date: 2025-12-12 18:52:37.738217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a757914543ac'
down_revision: Union[str, Sequence[str], None] = 'add_email_parsing'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('income_analytics')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('income_analytics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_income_30d', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True),
    sa.Column('total_income_90d', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True),
    sa.Column('avg_monthly_income', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True),
    sa.Column('income_volatility', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('monthly_income', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('income_sources', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('month_classifications', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('income_expense_ratios', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('current_buffer_days', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('recommended_buffer_days', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('buffer_status', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('good_months_streak', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('bad_months_streak', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('income_trend', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('last_income_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_updated', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('income_transaction_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('income_analytics_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('income_analytics_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('income_analytics_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
